default:
  image: registry.redhat.io/openshift4/ose-cli:latest

build:
  script:
    - oc get builds -n hello-world
    - oc logs hello-world-3-build -n hello-world
    - oc start-build hello-world -n hello-world
