default:
  image: registry.redhat.io/openshift4/ose-cli:latest

build:
  script:
    - oc start-build "hello-world-${CI_COMMIT_BRANCH}" \
        --namespace hello-world \
        --follow \
        --wait
  only:
    - dev
    - test1
    - test2
    - main
