default:
  image: registry.redhat.io/openshift4/ose-cli:latest

s2i:
  script:
    - oc login https://api.ocp.taco.moe:6443 --token="${OPENSHIFT_API_TOKEN}" --insecure-skip-tls-verify
    - oc get buildconfigs
