default:
  image: registry.redhat.io/openshift4/ose-cli:latest

build:
  script:
    # - sleep 5000
    # - oc logs hello-world-build-3 -n hello-world --follow
    - env
    - exit 1
    - oc start-build hello-world -n hello-world --wait --follow
