default:
  image: registry.redhat.io/openshift4/ose-cli:latest

build:
  script:
    - echo "$CI_COMMIT_BRANCH"
    - oc start-build "hello-world-$CI_COMMIT_BRANCH" \
        --namespace hello-world-dev \
        --follow \
        --wait
  only:
    - dev
    - test1
    - test2
    - main
