apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-world
  namespace: hello-world
spec:
  failedBuildsHistoryLimit: 5
  output:
    pushSecret:
      name: push-secret # This needs to be created
    to:
      kind: DockerImage
      name: quay-registry-quay-quay-enterprise.apps.hub.taco.moe/hello-world/hello-world:latest
  runPolicy: Serial
  source:
    git:
      uri: https://git.taco.moe/lab/hello-world-spring-boot.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-17-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: ZzSAP__BE3UpCeLXAONI
    type: GitHub
  - generic:
      secret: FRkkkXfV6ZAXjzDMix1w
    type: Generic
  - type: ConfigChange
  - type: ImageChange
